### ISSUE TITLE
unexpected keyword argument 'api_key'

### ISSUE THREAD

**Issue by azaprudska** [coinpaprika/coinpaprika-api-python-client#5]
Hey! 

I'm trying to initiate Coinpaprika Python Client with an API access key as in README, but I'm getting the error: 

![Screenshot 2023-06-21 at 4 57 05 PM](https://github.com/coinpaprika/coinpaprika-api-python-client/assets/95703667/42ec9f22-7e91-4537-b4cd-6bbf901cd10d)

Do you have any ideas why and how to solve it?

**Comment by r--w** [comment]
@azaprudska  We have just added package to pypi and updated README file,
 Pypi package name has changed to `coinpaprika-sdk`
